// Índice do Vade Mecum. Gerado por tools\converter-leis.ps1 a partir de leis-origem\ (Planalto e OAB). Confira sempre a versão atual na fonte.
window.C48_LEIS_IDX = [
    {
        "id":  "estatuto",
        "nome":  "Estatuto da Advocacia e da OAB (Lei 8.906/1994)",
        "curto":  "Estatuto da OAB",
        "grupo":  "Ética",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8906.htm",
        "captura":  "2026-10-04",
        "n":  96,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "regulamento",
        "nome":  "Regulamento Geral do Estatuto da Advocacia e da OAB",
        "curto":  "Regulamento Geral",
        "grupo":  "Ética",
        "fonte":  "OAB",
        "url":  "https://www.oab.org.br/publicacoes/AbrirPDF?LivroId=0000004095",
        "captura":  "2026-10-04",
        "n":  175,
        "aviso":  "Texto extraído de PDF: notas de rodapé e números de página podem aparecer no meio do texto, e alguns artigos podem vir juntos. Confira na fonte."
    },
    {
        "id":  "ced",
        "nome":  "Código de Ética e Disciplina da OAB",
        "curto":  "Código de Ética",
        "grupo":  "Ética",
        "fonte":  "OAB",
        "url":  "https://www.oab.org.br/publicacoes/AbrirPDF?LivroId=0000004085",
        "captura":  "2026-10-04",
        "n":  86,
        "aviso":  "Texto extraído de PDF: notas de rodapé e números de página podem aparecer no meio do texto, e alguns artigos podem vir juntos. Confira na fonte."
    },
    {
        "id":  "cf",
        "nome":  "Constituição Federal de 1988",
        "curto":  "Constituição",
        "grupo":  "Constitucional",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
        "captura":  "2026-10-04",
        "n":  411,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "cp",
        "nome":  "Código Penal (Decreto-Lei 2.848/1940)",
        "curto":  "Código Penal",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848compilado.htm",
        "captura":  "2026-10-04",
        "n":  424,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "cpp",
        "nome":  "Código de Processo Penal (Decreto-Lei 3.689/1941)",
        "curto":  "Proc. Penal",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689compilado.htm",
        "captura":  "2026-10-04",
        "n":  846,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "cc",
        "nome":  "Código Civil (Lei 10.406/2002)",
        "curto":  "Código Civil",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm",
        "captura":  "2026-10-04",
        "n":  2082,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "cpc",
        "nome":  "Código de Processo Civil (Lei 13.105/2015)",
        "curto":  "Proc. Civil",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm",
        "captura":  "2026-10-04",
        "n":  1073,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "clt",
        "nome":  "Consolidação das Leis do Trabalho (Decreto-Lei 5.452/1943)",
        "curto":  "CLT",
        "grupo":  "Trabalho",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm",
        "captura":  "2026-10-04",
        "n":  838,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "cdc",
        "nome":  "Código de Defesa do Consumidor (Lei 8.078/1990)",
        "curto":  "CDC",
        "grupo":  "Consumidor e ECA",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8078compilado.htm",
        "captura":  "2026-10-04",
        "n":  130,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "eca",
        "nome":  "Estatuto da Criança e do Adolescente (Lei 8.069/1990)",
        "curto":  "ECA",
        "grupo":  "Consumidor e ECA",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8069.htm",
        "captura":  "2026-10-04",
        "n":  327,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "ctn",
        "nome":  "Código Tributário Nacional (Lei 5.172/1966)",
        "curto":  "CTN",
        "grupo":  "Tributário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm",
        "captura":  "2026-10-04",
        "n":  231,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l14133",
        "nome":  "Lei de Licitações e Contratos (Lei 14.133/2021)",
        "curto":  "Licitações",
        "grupo":  "Administrativo",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm",
        "captura":  "2026-10-04",
        "n":  196,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8429",
        "nome":  "Lei de Improbidade Administrativa (Lei 8.429/1992)",
        "curto":  "Improbidade",
        "grupo":  "Administrativo",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8429.htm",
        "captura":  "2026-10-04",
        "n":  31,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9784",
        "nome":  "Processo Administrativo Federal (Lei 9.784/1999)",
        "curto":  "Proc. Administrativo",
        "grupo":  "Administrativo",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9784.htm",
        "captura":  "2026-10-04",
        "n":  80,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8987",
        "nome":  "Concessões e Permissões (Lei 8.987/1995)",
        "curto":  "Concessões",
        "grupo":  "Administrativo",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8987cons.htm",
        "captura":  "2026-10-04",
        "n":  52,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l11079",
        "nome":  "Parcerias Público-Privadas (Lei 11.079/2004)",
        "curto":  "PPP",
        "grupo":  "Administrativo",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2004/lei/l11079.htm",
        "captura":  "2026-10-04",
        "n":  32,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l11101",
        "nome":  "Recuperação e Falência (Lei 11.101/2005)",
        "curto":  "Falência",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11101.htm",
        "captura":  "2026-10-04",
        "n":  260,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9279",
        "nome":  "Propriedade Industrial (Lei 9.279/1996)",
        "curto":  "Prop. Industrial",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9279.htm",
        "captura":  "2026-10-04",
        "n":  247,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l6404",
        "nome":  "Lei das Sociedades por Ações (Lei 6.404/1976)",
        "curto":  "Lei das S.A.",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l6404consol.htm",
        "captura":  "2026-10-04",
        "n":  305,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l7357",
        "nome":  "Lei do Cheque (Lei 7.357/1985)",
        "curto":  "Cheque",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l7357.htm",
        "captura":  "2026-10-04",
        "n":  71,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l5474",
        "nome":  "Lei da Duplicata (Lei 5.474/1968)",
        "curto":  "Duplicata",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l5474.htm",
        "captura":  "2026-10-04",
        "n":  24,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l13966",
        "nome":  "Lei da Franquia (Lei 13.966/2019)",
        "curto":  "Franquia",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2019/lei/l13966.htm",
        "captura":  "2026-10-04",
        "n":  10,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l4886",
        "nome":  "Representação Comercial (Lei 4.886/1965)",
        "curto":  "Representação",
        "grupo":  "Empresarial",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l4886.htm",
        "captura":  "2026-10-04",
        "n":  49,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8213",
        "nome":  "Benefícios da Previdência Social (Lei 8.213/1991)",
        "curto":  "Benefícios INSS",
        "grupo":  "Previdenciário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8213cons.htm",
        "captura":  "2026-10-04",
        "n":  156,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8742",
        "nome":  "Assistência Social - LOAS (Lei 8.742/1993)",
        "curto":  "LOAS",
        "grupo":  "Previdenciário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8742.htm",
        "captura":  "2026-10-04",
        "n":  68,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l6938",
        "nome":  "Política Nacional do Meio Ambiente (Lei 6.938/1981)",
        "curto":  "Meio Ambiente",
        "grupo":  "Ambiental",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm",
        "captura":  "2026-10-04",
        "n":  26,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9605",
        "nome":  "Crimes Ambientais (Lei 9.605/1998)",
        "curto":  "Crimes Ambientais",
        "grupo":  "Ambiental",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
        "captura":  "2026-10-04",
        "n":  87,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9985",
        "nome":  "Unidades de Conservação - SNUC (Lei 9.985/2000)",
        "curto":  "SNUC",
        "grupo":  "Ambiental",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9985.htm",
        "captura":  "2026-10-04",
        "n":  62,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l12651",
        "nome":  "Código Florestal (Lei 12.651/2012)",
        "curto":  "Código Florestal",
        "grupo":  "Ambiental",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/l12651.htm",
        "captura":  "2026-10-04",
        "n":  91,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l13445",
        "nome":  "Lei de Migração (Lei 13.445/2017)",
        "curto":  "Migração",
        "grupo":  "Internacional",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/lei/l13445.htm",
        "captura":  "2026-10-04",
        "n":  125,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9474",
        "nome":  "Estatuto dos Refugiados (Lei 9.474/1997)",
        "curto":  "Refugiados",
        "grupo":  "Internacional",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9474.htm",
        "captura":  "2026-10-04",
        "n":  49,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "lindb",
        "nome":  "LINDB (Decreto-Lei 4.657/1942)",
        "curto":  "LINDB",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto-lei/del4657compilado.htm",
        "captura":  "2026-10-04",
        "n":  30,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9504",
        "nome":  "Lei das Eleições (Lei 9.504/1997)",
        "curto":  "Lei das Eleições",
        "grupo":  "Eleitoral",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9504.htm",
        "captura":  "2026-10-04",
        "n":  143,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "lc64",
        "nome":  "Inelegibilidades (LC 64/1990)",
        "curto":  "Inelegibilidades",
        "grupo":  "Eleitoral",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp64.htm",
        "captura":  "2026-10-04",
        "n":  33,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l4737",
        "nome":  "Código Eleitoral (Lei 4.737/1965)",
        "curto":  "Código Eleitoral",
        "grupo":  "Eleitoral",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l4737compilado.htm",
        "captura":  "2026-10-04",
        "n":  385,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l4320",
        "nome":  "Normas de Direito Financeiro (Lei 4.320/1964)",
        "curto":  "Lei 4.320",
        "grupo":  "Financeiro",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l4320.htm",
        "captura":  "2026-10-04",
        "n":  87,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "lc101",
        "nome":  "Lei de Responsabilidade Fiscal (LC 101/2000)",
        "curto":  "LRF",
        "grupo":  "Financeiro",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp101.htm",
        "captura":  "2026-10-04",
        "n":  83,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8072",
        "nome":  "Crimes Hediondos (Lei 8.072/1990)",
        "curto":  "Hediondos",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8072.htm",
        "captura":  "2026-10-04",
        "n":  13,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l11343",
        "nome":  "Lei de Drogas (Lei 11.343/2006)",
        "curto":  "Drogas",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11343.htm",
        "captura":  "2026-10-04",
        "n":  100,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l10826",
        "nome":  "Estatuto do Desarmamento (Lei 10.826/2003)",
        "curto":  "Desarmamento",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/2003/l10.826.htm",
        "captura":  "2026-10-04",
        "n":  41,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9099",
        "nome":  "Juizados Especiais (Lei 9.099/1995)",
        "curto":  "Juizados",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9099.htm",
        "captura":  "2026-10-04",
        "n":  99,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l7210",
        "nome":  "Lei de Execução Penal (Lei 7.210/1984)",
        "curto":  "LEP",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l7210.htm",
        "captura":  "2026-10-04",
        "n":  218,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9503",
        "nome":  "Código de Trânsito (Lei 9.503/1997)",
        "curto":  "CTB",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9503compilado.htm",
        "captura":  "2026-10-04",
        "n":  390,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l9296",
        "nome":  "Interceptação Telefônica (Lei 9.296/1996)",
        "curto":  "Interceptação",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l9296.htm",
        "captura":  "2026-10-04",
        "n":  14,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l12850",
        "nome":  "Organizações Criminosas (Lei 12.850/2013)",
        "curto":  "Org. Criminosas",
        "grupo":  "Penal",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2013/lei/l12850.htm",
        "captura":  "2026-10-04",
        "n":  36,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l6830",
        "nome":  "Execução Fiscal (Lei 6.830/1980)",
        "curto":  "Execução Fiscal",
        "grupo":  "Tributário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l6830.htm",
        "captura":  "2026-10-04",
        "n":  42,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "d70235",
        "nome":  "Processo Administrativo Fiscal (Decreto 70.235/1972)",
        "curto":  "PAF",
        "grupo":  "Tributário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto/d70235cons.htm",
        "captura":  "2026-10-04",
        "n":  73,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "lc116",
        "nome":  "Lei do ISS (LC 116/2003)",
        "curto":  "ISS",
        "grupo":  "Tributário",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm",
        "captura":  "2026-10-04",
        "n":  12,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8245",
        "nome":  "Lei do Inquilinato (Lei 8.245/1991)",
        "curto":  "Locações",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8245.htm",
        "captura":  "2026-10-04",
        "n":  91,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l12016",
        "nome":  "Mandado de Segurança (Lei 12.016/2009)",
        "curto":  "Mandado de Segurança",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/lei/l12016.htm",
        "captura":  "2026-10-04",
        "n":  29,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l7347",
        "nome":  "Ação Civil Pública (Lei 7.347/1985)",
        "curto":  "Ação Civil Pública",
        "grupo":  "Civil",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l7347orig.htm",
        "captura":  "2026-10-04",
        "n":  23,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l10741",
        "nome":  "Estatuto da Pessoa Idosa (Lei 10.741/2003)",
        "curto":  "Pessoa Idosa",
        "grupo":  "Direitos Humanos",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm",
        "captura":  "2026-10-04",
        "n":  118,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l13146",
        "nome":  "Estatuto da Pessoa com Deficiência (Lei 13.146/2015)",
        "curto":  "Pessoa com Deficiência",
        "grupo":  "Direitos Humanos",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13146.htm",
        "captura":  "2026-10-04",
        "n":  130,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l12288",
        "nome":  "Estatuto da Igualdade Racial (Lei 12.288/2010)",
        "curto":  "Igualdade Racial",
        "grupo":  "Direitos Humanos",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12288.htm",
        "captura":  "2026-10-04",
        "n":  65,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "d678",
        "nome":  "Convenção Americana de Direitos Humanos (Decreto 678/1992)",
        "curto":  "Pacto de San José",
        "grupo":  "Direitos Humanos",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/decreto/d0678.htm",
        "captura":  "2026-10-04",
        "n":  82,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "d6949",
        "nome":  "Convenção sobre Pessoas com Deficiência (Decreto 6.949/2009)",
        "curto":  "Conv. Deficiência",
        "grupo":  "Direitos Humanos",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2009/decreto/d6949.htm",
        "captura":  "2026-10-04",
        "n":  50,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l6019",
        "nome":  "Trabalho Temporário (Lei 6.019/1974)",
        "curto":  "Temporário",
        "grupo":  "Trabalho",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l6019.htm",
        "captura":  "2026-10-04",
        "n":  30,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "lc150",
        "nome":  "Empregado Doméstico (LC 150/2015)",
        "curto":  "Doméstico",
        "grupo":  "Trabalho",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp150.htm",
        "captura":  "2026-10-04",
        "n":  48,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l7783",
        "nome":  "Lei de Greve (Lei 7.783/1989)",
        "curto":  "Greve",
        "grupo":  "Trabalho",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l7783.htm",
        "captura":  "2026-10-04",
        "n":  19,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    },
    {
        "id":  "l8036",
        "nome":  "FGTS (Lei 8.036/1990)",
        "curto":  "FGTS",
        "grupo":  "Trabalho",
        "fonte":  "Planalto",
        "url":  "https://www.planalto.gov.br/ccivil_03/leis/l8036consol.htm",
        "captura":  "2026-10-04",
        "n":  48,
        "aviso":  "Texto compilado do Planalto, sem os trechos riscados (revogados ou suspensos). Confira a versão em vigor na fonte."
    }
];
